// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2eZR4KYAdU3mugvjN-RzodxTgBHCM7o',
    appId: '1:816368262190:web:b28bfd7c716f5698bd53bf',
    messagingSenderId: '816368262190',
    projectId: 'college-app-99688',
    authDomain: 'college-app-99688.firebaseapp.com',
    storageBucket: 'college-app-99688.firebasestorage.app',
    measurementId: 'G-D36JLFQ47K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtktUrk4cvU-joa1hWWi6LIdeSS8jh9-c',
    appId: '1:816368262190:android:37f42338e0655622bd53bf',
    messagingSenderId: '816368262190',
    projectId: 'college-app-99688',
    storageBucket: 'college-app-99688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFB8wwjNJWGcMNc_szUM1EkwkDR_fieSg',
    appId: '1:816368262190:ios:4d9b12c6e5a5aa9abd53bf',
    messagingSenderId: '816368262190',
    projectId: 'college-app-99688',
    storageBucket: 'college-app-99688.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFB8wwjNJWGcMNc_szUM1EkwkDR_fieSg',
    appId: '1:816368262190:ios:4d9b12c6e5a5aa9abd53bf',
    messagingSenderId: '816368262190',
    projectId: 'college-app-99688',
    storageBucket: 'college-app-99688.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm2eZR4KYAdU3mugvjN-RzodxTgBHCM7o',
    appId: '1:816368262190:web:68c3bec4338623adbd53bf',
    messagingSenderId: '816368262190',
    projectId: 'college-app-99688',
    authDomain: 'college-app-99688.firebaseapp.com',
    storageBucket: 'college-app-99688.firebasestorage.app',
    measurementId: 'G-9FJEWJL8XW',
  );
}
